import Head from 'next/head'
interface IProps {
  title?: string
}
export default function Home({
  title = 'Boilerplate - NextJs/Typescript'
}: IProps) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World</h1>
      </main>
    </>
  )
}
